// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton'];
    Hello: typeof import('./src/components/Hello/Hello.vue')['default'];
    I18nExample: typeof import('./src/components/I18nExample/I18nExample.vue')['default'];
  }
}

export {};
